### ISSUE TITLE
windows builders are confused

### ISSUE THREAD

**Issue by mrjbq7** [slavapestov/factor#1343]
They don't know what is in ``core/`` for some reason.

```
Boot image is out of date. Changed vocabs:
windows.com
```

**Comment by erg** [comment]
Windows processes launch relative to their parent process binary location, not to the current directory. Mason is launching the child instance as ``./factor.com``, which is ``c:\\factor\\factor.com``, but the ``lpCurrentDirectory`` of that child process is the new source in ``c:\\users\\erg\\builds\\date\\factor\\``.

Fix is to use absolute path of child mason ``factor.com``.

We never noticed this before because most commands are in the global path on Windows, ``factor.com`` is in the mason directory too, and because in other instances we must have used full pathnames.

**Comment by erg** [comment]
Fixed by 2451fea0a131eb681e95ab0d5bbf6eb7d9f0ed8f.
