### ISSUE TITLE
.factor-boot-rc not being executed?

### ISSUE THREAD

**Issue by rogerlevy** [slavapestov/factor#1462]
Am I confused about something?  I thought this file was supposed to be loaded in addition to .factor-rc, (presumably once the Listener has already started)  

The thing is the more USE:'s and require's I add to .factor-rc the longer it takes for the Listener to even show up.  Visual feedback is preferable.

Anyway it seems that the .factor-boot-rc isn't being loaded at all.

I would like to have certain vocabularies loaded automatically and already in the search order of the Listener when I startup Factor.

**Comment by erg** [comment]
.factor-boot-rc loads after bootstrap. You can fire up factor and do
``run-bootstrap-init save`` to do it manually.

**Comment by rogerlevy** [comment]
Thanks, so I understand that saving the image would "bake" the desired vocabs into the image but that's not what I want.

What does "loads after bootstrap" mean?  To me that sounds like it should load it after Factor has bootstrapped i.e. started up (which isn't happening) but I guess I must have it wrong.

**Comment by erg** [comment]
Bootstrapping is when factor makes a new factor.image from a previous boot image.

```
! Bootstrapping
./factor -i=boot.unix-x86.64.image
! .factor-boot-rc runs when the above line finishes

! Startup
./factor
! .factor-rc runs on startup
```

**Comment by rogerlevy** [comment]
OK, thanks.

**Comment by erg** [comment]
Closing I guess. Cheers!

**Comment by mrjbq7** [comment]
@rogerlevy running ``save`` in the listener after ``USE:`` will "bake" as you say the vocabularies into the image, so that they are available immediately upon startup without requiring the delay loading them upon the next startup.

In that respect, having them in ``.factor-rc`` is fine because the ``USE:`` instruction will check to see if the vocabulary is loaded, and only load it if it is not.

P.S., we love hearing about stuff like this so feel free to open more bug reports.  The documentation for bootstrap could probably use some work:

http://docs.factorcode.org/content/article-bootstrap.image.html

Also some more info on the three "dot files" that Factor uses:

http://docs.factorcode.org/content/article-rc-files.html
